sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "kubernetes-bruno-study"
  env: "KubernetesBrunoStudy-env"
  bucket_name: "elasticbeanstalk-us-west-2-500849232025"
  bucket_path: "kubernetes-bruno-study"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
